version: '3'

services:
    
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb   
    ports:
      - "27017:27017"
    restart: unless-stopped       
    environment:
      - MONGODB_ROOT_PASSWORD=p4ssw0rd
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=p4ssw0rd
    volumes:
      - ./mongo-data:/data/db
      