version: '3'

services:
    
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb   
    ports:
      - "27017:27017"
    restart: unless-stopped       
    environment:
      - MONGODB_ROOT_PASSWORD=p4ssw0rd
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=p4ssw0rd
    volumes:
      - ./mongo-data:/data/db
      
  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    container_name: mongo-express    
    ports:
      - "8080:8081"
    restart: unless-stopped       
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=p4ssw0rd
      - ME_CONFIG_MONGODB_SERVER=mongodb